import { useEffect, useMemo, useState } from 'react';
import { Container, Spinner } from 'react-bootstrap';
import { Link } from 'react-router-dom';
import { API, fetchProducts, fetchProductsByCategory } from '../services/api';
const categories=['Writing Things','Books & Notes','Electronics','Toys','Story Books','School Bags']; const apiOrigin=API.replace(/\/api$/,'');
export default function EcommerceHomePage(){
 const [products,setProducts]=useState([]),[category,setCategory]=useState(''),[search,setSearch]=useState(''),[sort,setSort]=useState('newest'),[brand,setBrand]=useState(''),[delivery,setDelivery]=useState(''),[minPrice,setMinPrice]=useState(''),[maxPrice,setMaxPrice]=useState(''),[cart,setCart]=useState([]),[loading,setLoading]=useState(true),[error,setError]=useState('');
 useEffect(()=>{let active=true;setLoading(true);const params={search,sort,brand,minPrice,maxPrice,limit:100};(category?fetchProductsByCategory(category,params):fetchProducts(params)).then(d=>active&&setProducts(d.items||[])).catch(e=>active&&setError(e.message)).finally(()=>active&&setLoading(false));return()=>{active=false}},[category,search,sort,brand,minPrice,maxPrice]);
 const visible=useMemo(()=>products.filter(p=>!delivery||(delivery==='fast'?p.fastDelivery:p.smoothDelivery)),[products,delivery]); const brands=[...new Set(products.map(p=>p.brand).filter(Boolean))];
 return <div className="shop-page"><section className="shop-hero"><Container fluid="xl"><div className="shop-hero__content"><span className="home-hero__label">Student Store</span><h1>Everything students need, in one place.</h1><p>Choose a product and complete a secure student checkout.</p></div><aside className="shop-cart-summary"><span>Cart Items</span><strong>{cart.length}</strong><p>Rs. {cart.reduce((sum,p)=>sum+p.finalPrice,0).toFixed(2)}</p></aside></Container></section><section className="shop-products"><Container fluid="xl"><nav className="shop-category-nav"><button className={!category?'active':''} onClick={()=>setCategory('')}>All</button>{categories.map(c=><button className={category===c?'active':''} key={c} onClick={()=>setCategory(c)}>{c}</button>)}</nav><div className="shop-filters"><input type="search" placeholder="Search products" value={search} onChange={e=>setSearch(e.target.value)}/><select value={sort} onChange={e=>setSort(e.target.value)}><option value="newest">Newest</option><option value="priceAsc">Price Low to High</option><option value="priceDesc">Price High to Low</option><option value="discount">Highest Discount</option></select><select value={brand} onChange={e=>setBrand(e.target.value)}><option value="">All Brands</option>{brands.map(b=><option key={b}>{b}</option>)}</select><select value={delivery} onChange={e=>setDelivery(e.target.value)}><option value="">All Delivery</option><option value="fast">Fast Delivery</option><option value="smooth">Smooth Delivery</option></select><input type="number" placeholder="Min price" value={minPrice} onChange={e=>setMinPrice(e.target.value)}/><input type="number" placeholder="Max price" value={maxPrice} onChange={e=>setMaxPrice(e.target.value)}/></div>{loading?<div className="shop-state"><Spinner animation="border"/> Loading products...</div>:error?<div className="alert alert-danger">{error}</div>:!visible.length?<div className="shop-state">No products match these filters.</div>:<div className="shop-product-grid">{visible.map(p=><article className="shop-product-card" key={p._id}><img className="shop-product-image" src={p.image?.startsWith('http')?p.image:`${apiOrigin}${p.image}`} alt={p.name}/><div className="shop-product-card__body"><span className="shop-product-card__type">{p.category}</span><h3>{p.name}</h3><p>{p.description}</p><div className="delivery-badges">{p.fastDelivery&&<span>Fast Delivery</span>}{p.smoothDelivery&&<span>Smooth Delivery</span>}</div><div className="product-prices"><del>Rs. {p.price}</del><span>{p.discount}% off</span><strong>Rs. {p.finalPrice}</strong></div><div className="product-actions"><button onClick={()=>setCart(items=>[...items,p])}>Add to Cart</button><Link to="/ecommerce-orders" state={{product:p}}>Buy Now</Link></div></div></article>)}</div>}</Container></section></div>;
}
