import { useEffect, useState } from 'react';
import { Container } from 'react-bootstrap';
import { Link, useLocation, useNavigate } from 'react-router-dom';
import { API, createOrder, fetchMyOrders } from '../services/api';
import { readStudentSession } from '../services/studentSession';

export default function EcommerceOrderPage(){
 const {state}=useLocation(),navigate=useNavigate(),session=readStudentSession(),product=state?.product;
 const [form,setForm]=useState({name:session?.user?.name||'',email:session?.user?.email||'',phone:'',address:'',paymentMode:'COD',quantity:1,upiId:'',cardNumber:'',cardName:'',expiry:'',cvv:''}),[loading,setLoading]=useState(false),[error,setError]=useState(''),[completed,setCompleted]=useState(null);
 const [orders,setOrders]=useState([]),[ordersLoading,setOrdersLoading]=useState(Boolean(session?.token)),[ordersError,setOrdersError]=useState('');
 useEffect(()=>{if(!session?.token)return;fetchMyOrders(session.token).then(data=>setOrders(data.items||[])).catch(err=>setOrdersError(err.message)).finally(()=>setOrdersLoading(false));},[session?.token,completed]);
 const change=e=>setForm(current=>({...current,[e.target.name]:e.target.value}));
 const submit=async e=>{e.preventDefault();if(!session?.token){navigate('/student-login',{state:{message:'Please login before buying a product.'}});return}if(form.paymentMode==='UPI'&&!/^[\w.-]+@[\w.-]+$/.test(form.upiId))return setError('Enter a valid UPI ID.');if(form.paymentMode==='Card'&&(!/^\d{16}$/.test(form.cardNumber.replace(/\s/g,''))||!/^\d{3,4}$/.test(form.cvv)))return setError('Enter valid card details.');setLoading(true);setError('');try{const data=await createOrder({productId:product._id,quantity:Number(form.quantity),name:form.name,email:form.email,phone:form.phone,address:form.address,paymentMode:form.paymentMode},session.token);setCompleted(data.order)}catch(err){setError(err.message)}finally{setLoading(false)}};
 if(!product&&!completed)return <section className="order-workspace"><Container fluid="xl"><div className="order-panel customer-orders-page"><span className="home-hero__label">Customer Orders</span><h1>Your ecommerce order details</h1>{!session?.token?<div className="orders-empty"><p>Login with your student account to view payment and delivery details.</p><Link to="/student-login" state={{message:'Please login to view your ecommerce orders.'}} className="checkout-submit">Student Login</Link></div>:ordersLoading?<p>Loading your orders...</p>:ordersError?<div className="alert alert-danger">{ordersError}</div>:!orders.length?<div className="orders-empty"><p>You have not placed an order yet.</p><Link to="/ecommerce" className="checkout-submit">Shop Products</Link></div>:<OrderDetails orders={orders}/>}<div className="customer-orders-actions"><Link to="/ecommerce">Continue Shopping</Link>{session?.token&&<Link to="/student-login" state={{panel:'orders'}}>Open Student Dashboard</Link>}</div></div></Container></section>;
 if(completed)return <section className="order-workspace"><Container fluid="xl"><div className="checkout-success"><span>✓</span><h1>Order completed</h1><p>Your order <strong>{completed.orderNumber}</strong> was placed successfully.</p><p>{completed.paymentMode==='COD'?'Payment will be collected on delivery.':'Payment completed successfully.'}</p><div><button onClick={()=>navigate('/student-login')}>View Your Orders</button><Link to="/ecommerce">Continue Shopping</Link></div></div></Container></section>;
 const image=/^(https?:|data:)/i.test(product.image || '')?product.image:`${API.replace(/\/api$/,'')}${product.image}`; const total=(Number(product.finalPrice)*Number(form.quantity||1)).toFixed(2);
 return <div className="order-page"><section className="order-hero"><Container fluid="xl"><span className="home-hero__label">Secure Checkout</span><h1>Complete your order</h1><p>Enter delivery details and choose COD, UPI, or card payment.</p></Container></section><section className="order-workspace"><Container fluid="xl"><div className="checkout-layout"><aside className="order-panel checkout-product"><img src={image} alt={product.name}/><h2>{product.name}</h2><p>{product.description}</p><label>Quantity<input type="number" name="quantity" min="1" max={product.stock} value={form.quantity} onChange={change}/></label><strong>Order total: Rs. {total}</strong></aside><form className="order-panel checkout-form" onSubmit={submit}><h2>Delivery details</h2>{error&&<div className="alert alert-danger">{error}</div>}<div className="checkout-grid"><label>Full name<input name="name" value={form.name} onChange={change} required/></label><label>Email<input type="email" name="email" value={form.email} onChange={change} required/></label><label>Phone<input type="tel" name="phone" pattern="[+0-9][0-9 -]{7,14}" value={form.phone} onChange={change} required/></label><label className="checkout-wide">Delivery address<textarea name="address" rows="4" value={form.address} onChange={change} required/></label></div><h2>Payment mode</h2><div className="checkout-payment">{['COD','UPI','Card'].map(mode=><label key={mode}><input type="radio" name="paymentMode" value={mode} checked={form.paymentMode===mode} onChange={change}/><span>{mode==='COD'?'Cash on Delivery':mode}</span></label>)}</div>{form.paymentMode==='UPI'&&<label>UPI ID<input name="upiId" placeholder="name@bank" value={form.upiId} onChange={change} required/></label>}{form.paymentMode==='Card'&&<div className="checkout-grid"><label className="checkout-wide">Card number<input name="cardNumber" inputMode="numeric" maxLength="19" value={form.cardNumber} onChange={change} required/></label><label>Name on card<input name="cardName" value={form.cardName} onChange={change} required/></label><label>Expiry<input name="expiry" placeholder="MM/YY" value={form.expiry} onChange={change} required/></label><label>CVV<input type="password" name="cvv" maxLength="4" value={form.cvv} onChange={change} required/></label></div>}<button className="checkout-submit" disabled={loading}>{loading?'Completing order...':form.paymentMode==='COD'?'Place COD Order':`Pay Rs. ${total}`}</button></form></div></Container></section></div>;
}

function OrderDetails({orders}){
 const steps=['Order Confirmed','Packed','Shipped','Out for Delivery','Delivered'],origin=API.replace(/\/api$/,'');
 return <div className="customer-order-list">{orders.map(order=>{const active=steps.indexOf(order.orderStatus);const image=/^(https?:|data:)/i.test(order.productImage||'')?order.productImage:`${origin}${order.productImage}`;return <article className="customer-order-card" key={order._id}><img src={image} alt={order.productName}/><div className="customer-order-card__details"><span>Order {order.orderNumber}</span><h2>{order.productName}</h2><p><strong>Customer:</strong> {order.name}</p><p><strong>Delivery:</strong> {order.address}</p><p>{order.quantity} × Rs. {order.unitPrice} · {order.paymentMode} · Payment {order.paymentStatus}</p><strong className="customer-order-total">Rs. {order.totalAmount}</strong></div><b className="customer-order-status">{order.orderStatus}</b><div className="customer-order-track">{steps.map((step,index)=><span className={index<=active?'active':''} key={step}>{step}</span>)}</div></article>})}</div>;
}
