import fs from 'node:fs';
import path from 'node:path';
import { Router } from 'express';
import multer from 'multer';
import { createCounselling, deleteAdminCounselling, deleteStudentCounselling, getAdminCounselling, getStudentCounselling, listAdminCounselling, listNotifications, listStudentCounselling, readNotification, updateAdminCounselling, updateStudentCounselling } from '../controllers/counsellingController.js';
import { requireStudent } from '../middleware/counsellingAuth.js';

const directory = path.resolve(process.env.UPLOAD_DIR || 'uploads', 'counselling');
fs.mkdirSync(directory, { recursive: true });
const upload = multer({ storage: multer.diskStorage({ destination: directory, filename: (_req, file, cb) => cb(null, `${Date.now()}-${file.originalname.replace(/[^a-zA-Z0-9.-]/g, '-')}`) }), limits: { fileSize: 5 * 1024 * 1024 }, fileFilter: (_req, file, cb) => { const ok = ['image/jpeg', 'image/png', 'image/webp'].includes(file.mimetype); cb(ok ? null : new Error('Only JPG, PNG, and WebP images are allowed.'), ok); } });
const router = Router();
router.post('/counselling', requireStudent, upload.single('image'), createCounselling);
router.get('/counselling', requireStudent, listStudentCounselling);
router.get('/counselling/:id', requireStudent, getStudentCounselling);
router.put('/counselling/:id', requireStudent, updateStudentCounselling);
router.delete('/counselling/:id', requireStudent, deleteStudentCounselling);
router.get('/admin/counselling', listAdminCounselling);
router.get('/admin/counselling/:id', getAdminCounselling);
router.put('/admin/counselling/:id', updateAdminCounselling);
router.patch('/admin/counselling/:id', updateAdminCounselling);
router.delete('/admin/counselling/:id', deleteAdminCounselling);
router.get('/notifications', requireStudent, listNotifications);
router.patch('/notifications/:id/read', requireStudent, readNotification);
export default router;
